main: com.nicolorancan.Main.Main
name: HttpPoster
version: 4.0
author: Rancan Nicolò

commands:
  httpposter:
    usage: /httpposter <command>
    permission: httpposter.help
    permission-message: You do not have permission to run this command